### ISSUE TITLE
Is that script working nowadays?

### ISSUE THREAD

**Issue by suprovsky** [acidsploit/mikrotik-routeros-scripts#2]
![image](https://user-images.githubusercontent.com/13705604/64906962-03bfb780-d6ed-11e9-98bd-fc073fdcd61d.png)
I supplied correct credentials, I checked whether they are working through the same site which is in the script but placed the data instead of variables and the change worked (got good IP_address message in return).

Could you please tell me if I am doing anything wrong here?

**Comment by acidsploit** [comment]
Sorry. Didn't notice this issue till now. Did you figure it out? Because I have this script running myself, so it should be working.

**Comment by suprovsky** [comment]
Yeah, it was my mistake. Just a typo in a login. Thanks for a notice.
